apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-builder-engine
  labels:
    app: chatbot-builder-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-builder-engine
  template:
    metadata:
      name: chatbot-builder-engine
      labels:
        app: chatbot-builder-engine
    spec:
      containers:
        - name: chatbot-builder-engine
          image: acrworkflow1729021672279.azurecr.io/chatbot-builder-engine
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: environment-config
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-secrets
                  key: SENTRY_DSN
          volumeMounts:
            - mountPath: /app/logs
              name: logs-volume
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc
      restartPolicy: Always
