apiVersion: v1
kind: Service
metadata:
  name: chatbot-builder-executor-service
spec:
  selector:
    app: chatbot-builder-executor
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      name: grpc