apiVersion: v1
kind: Service
metadata:
  name: api-sqlserver-service
spec:
  selector:
    app: chatbot-builder-api-sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  clusterIP: None
