apiVersion: v1
kind: Service
metadata:
  name: chatbot-builder-api-service
spec:
  selector:
    app: chatbot-builder-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: https
  loadBalancerIP: ${LOAD_BALANCER_IP}