apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-builder-api-sqlserver
  labels:
    app: chatbot-builder-api-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-builder-api-sqlserver
  template:
    metadata:
      labels:
        app: chatbot-builder-api-sqlserver
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: sqlserver-data-volume
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: sqlserver-data-volume
          persistentVolumeClaim:
            claimName: sqlserver-small-pvc
      restartPolicy: Always
