apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-builder-api
  labels:
    app: chatbot-builder-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-builder-api
  template:
    metadata:
      labels:
        app: chatbot-builder-api
    spec:
      containers:
        - name: chatbot-builder-api
          image: chatbot-builder-api
          ports:
            - containerPort: 8080
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: api-env-configmap
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SENTRY_DSN
            - name: ConnectionStrings__AppDbContextConnection
              value: "Server=api-sqlserver-service,1433;Database=master;User Id=sa;Password=cFj23uNY0lT&WP@t;TrustServerCertificate=True;"
          volumeMounts:
            - mountPath: /app/logs
              name: logs-volume
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc
      restartPolicy: Always