apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-builder-api
  labels:
    app: chatbot-builder-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-builder-api
  template:
    metadata:
      labels:
        app: chatbot-builder-api
    spec:
      containers:
        - name: chatbot-builder-api
          image: chatbot-builder-api
          ports:
            - containerPort: 8080
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: api-env-configmap
          env:
            - name: Sentry__WriteTo__1__Name
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SENTRY_DSN
            - name: Sentry__WriteTo__1__Args__MinimumEventLevel
              valueFrom:
                configMapKeyRef:
                  name: api-env-configmap
                  key: SENTRY_MINIMUM_EVENT_LEVEL
            - name: Sentry__WriteTo__1__Args__Environment
              valueFrom:
                configMapKeyRef:
                  name: api-env-configmap
                  key: ASPNETCORE_ENVIRONMENT
            - name: AzureBlobStorageSettings__AccountName
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: AZURE_BLOB_STORAGE_ACCOUNT_NAME
            - name: AzureBlobStorageSettings__AccountKey
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: AZURE_BLOB_STORAGE_ACCOUNT_KEY
            - name: AzureBlobStorageSettings__ContainerName
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: AZURE_BLOB_STORAGE_CONTAINER_NAME
            - name: ConnectionStrings__AppDbContextConnection
              valueFrom:
                configMapKeyRef:
                  key: SQLSERVER_CONNECTION_STRING
                  name: api-env-configmap
            - name: ExecutorService__Uri
              valueFrom:
                configMapKeyRef:
                  key: EXECUTOR_GRPC_ADDRESS
                  name: api-env-configmap
          volumeMounts:
            - mountPath: /app/logs
              name: logs-volume
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc
      restartPolicy: Always