apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-builder-api
  labels:
    app: chatbot-builder-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-builder-api
  template:
    metadata:
      labels:
        app: chatbot-builder-api
    spec:
      containers:
        - name: chatbot-builder-api
          image: chatbot-builder-api
          ports:
            - containerPort: 8080
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: api-env-configmap
          env:
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: SENTRY_DSN
            - name: DB_HOST
              value: api-sqlserver-service
            - name: DB_PORT
              value: "1433"
            - name: DB_NAME
              value: chatbot_builder_api_db
            - name: DB_USER
              value: sa
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: SA_PASSWORD
          volumeMounts:
            - mountPath: /app/logs
              name: logs-volume
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc
      restartPolicy: Always