apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: production
type: Opaque
data:
  SA_PASSWORD:
  SQLSERVER_CONNECTION_STRING:

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: staging
type: Opaque
data:
  SA_PASSWORD:
  SQLSERVER_CONNECTION_STRING:
