apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: production
type: Opaque
data:

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: staging
type: Opaque
data:
