name: Deploy to AKS

on:
  repository_dispatch:
    types:
      - deploy_chatbot_staging
      - deploy_chatbot_production

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Azure CLI Script - Get AKS Credentials
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME

    - name: Deploy to AKS - Apply manifests
      run: |
        # Determine environment and set the namespace accordingly
        if [[ "${{ github.event.action }}" == "deploy_chatbot_staging" ]]; then
          NAMESPACE="staging"
          LOAD_BALANCER_IP="${{ secrets.STAGING_LOAD_BALANCER_IP }}"
        elif [[ "${{ github.event.action }}" == "deploy_chatbot_production" ]]; then
          NAMESPACE="default"
          LOAD_BALANCER_IP="${{ secrets.PRODUCTION_LOAD_BALANCER_IP }}"
        else
          echo "Unknown event type. Exiting..."
          exit 1
        fi

        IMAGE_TAG="${{ github.event.client_payload.image_tag }}"
        echo "Deploying to namespace: $NAMESPACE with image: $IMAGE_TAG"

        # Update the manifest with the correct image tag
        sed -i 's|image: .*$|image: '"${{ secrets.ACR_LOGIN_SERVER }}/chatbot-builder-engine:${IMAGE_TAG}"'|' chatbot-builder-engine-deployment.yaml

        # Substitute the placeholder in the manifest with the actual load balancer IP
        sed -i 's|${LOAD_BALANCER_IP}|'"$LOAD_BALANCER_IP"'|' chatbot-builder-engine-service.yaml

        # Apply the deployment and service manifests to the correct namespace
        kubectl apply -n $NAMESPACE -f chatbot-builder-engine-deployment.yaml
        kubectl apply -n $NAMESPACE -f chatbot-builder-engine-service.yaml

    - name: Verify deployment status
      run: |
        # Determine environment and set the namespace accordingly
        if [[ "${{ github.event.action }}" == "deploy_chatbot_staging" ]]; then
          NAMESPACE="staging"
        elif [[ "${{ github.event.action }}" == "deploy_chatbot_production" ]]; then
          NAMESPACE="default"
        else
          echo "Unknown event type. Exiting..."
          exit 1
        fi

        # Debugging: Print the namespace for verification
        echo "Namespace is: $NAMESPACE"

        # If the namespace is empty, fail the build early
        if [ -z "$NAMESPACE" ]; then
          echo "Error: Namespace is not set."
          exit 1
        fi

        # Check the deployment rollout status
        kubectl rollout status deployment/chatbot-builder-engine -n ${NAMESPACE}
