name: Deploy Services to AKS

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy_chatbot]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the k8s repo
    - name: Checkout the k8s repo
      uses: actions/checkout@v2

    # Step 2: Login to Azure using OIDC (no need for secrets)
    - name: Azure login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true
        
    # Step 3: Set up Kubernetes context using AKS credentials
    - name: Get K8s context for AKS
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

    # Step 4: Check Kubernetes cluster info (debugging step)
    - name: Check Kubernetes Cluster Info
      run: |
        kubectl cluster-info

    # Step 5: Apply Kubernetes deployment and service manifests
    - name: Deploy Engine-Service to AKS
      run: |
        kubectl apply -f chatbot-builder-engine-deployment.yaml --validate=false
        kubectl apply -f chatbot-builder-engine-service.yaml --validate=false
