name: Deploy Services to AKS

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy_chatbot]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the k8s repo
    - name: Checkout k8s repo
      uses: actions/checkout@v2

    # Step 2: Display environment info for debugging
    - name: Display Environment Information
      run: |
        echo "Running on $(uname -a)"
        echo "Kubernetes Version: $(kubectl version --client)"
        echo "Current Directory: $(pwd)"
        ls -la

    # Step 3: Set up Kubernetes context using the server URL and token
    - name: Set up Kubernetes context with token and server
      run: |
        kubectl config set-credentials github-actions --token=${{ secrets.K8S_ACCESS_TOKEN }}
        kubectl config set-cluster aks-cluster --server=${{ secrets.K8S_SERVER_URL }}
        kubectl config set-context aks-context --cluster=aks-cluster --user=github-actions
        kubectl config use-context aks-context
    
    # Step 4: Show the Kubernetes config and verify the context
    - name: Show Kubernetes Config
      run: |
        kubectl config view
        kubectl config current-context

    # Step 5: Check Kubernetes cluster info for debugging
    - name: Check Kubernetes Cluster Info
      run: |
        kubectl cluster-info

    # Step 6: Apply Kubernetes deployment and service manifests
    - name: Deploy Engine-Service to AKS
      run: |
        kubectl apply -f chatbot-builder-engine-deployment.yaml --validate=false
        kubectl apply -f chatbot-builder-engine-service.yaml --validate=false
