name: Deploy Services to AKS

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy_chatbot]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the k8s repo
    - name: Checkout k8s repo
      uses: actions/checkout@v2

    # Step 2: Set up Kubernetes context with token and server URL
    - name: Set up Kubernetes context with token and server
      run: |
        kubectl config set-credentials github-actions --token=${{ secrets.K8S_ACCESS_TOKEN }}
        kubectl config set-cluster aks-cluster --server=${{ secrets.K8S_SERVER_URL }} --insecure-skip-tls-verify=true
        kubectl config set-context aks-context --cluster=aks-cluster --user=github-actions
        kubectl config use-context aks-context

    # Step 3: Check Kubernetes cluster info with token
    - name: Check Kubernetes Cluster Info
      run: |
        kubectl cluster-info --insecure-skip-tls-verify=true --token=${{ secrets.K8S_ACCESS_TOKEN }}

    # Step 4: Apply Kubernetes deployment and service manifests
    - name: Deploy Engine-Service to AKS
      run: |
        kubectl apply -f chatbot-builder-engine-deployment.yaml --validate=false --insecure-skip-tls-verify=true --token=${{ secrets.K8S_ACCESS_TOKEN }}
        kubectl apply -f chatbot-builder-engine-service.yaml --validate=false --insecure-skip-tls-verify=true --token=${{ secrets.K8S_ACCESS_TOKEN }}
