name: Deploy Services to AKS

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy_chatbot]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the k8s repo
    - name: Checkout k8s repo
      uses: actions/checkout@v2

    # Step 2: Display Environment Information
    - name: Display Environment Information
      run: |
        echo "Running on $(uname -a)"
        echo "Kubernetes Version: $(kubectl version --client)"
        echo "Current Directory: $(pwd)"
        ls -la

    # Step 3: Set up Kubernetes context with token
    - name: Set up Kubernetes context with token
      run: |
        kubectl config set-credentials github-actions --token=${{ secrets.K8S_ACCESS_TOKEN }}
        kubectl config set-context aks-context --cluster=${{ secrets.AKS_CLUSTER_NAME }} --user=github-actions
        kubectl config use-context aks-context
    
    # Debug Step: Show the kubectl configuration
    - name: Show Kubernetes Config
      run: |
        kubectl config view
        kubectl config current-context

    # Debug Step: Check Kubernetes cluster info
    - name: Check Kubernetes Cluster Info
      run: |
        kubectl cluster-info

    # Debug Step: Get all pods and services
    - name: List Pods and Services in Default Namespace
      run: |
        kubectl get pods --namespace default
        kubectl get services --namespace default

    # Step 4: Apply Kubernetes deployment and service manifests
    - name: Deploy Engine-Service to AKS
      run: |
        kubectl apply -f chatbot-builder-engine-deployment.yaml --validate=false
        kubectl apply -f chatbot-builder-engine-service.yaml --validate=false
