name: Deploy to AKS

on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - deploy_chatbot

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Azure CLI Script - Get AKS Credentials
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME

    - name: Restart deployment
      run: |
        kubectl rollout restart deployment chatbot-builder-engine

    - name: Verify deployment status
      run: |
        kubectl rollout status deployment chatbot-builder-engine
