apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: default
type: Opaque
data:
  SA_PASSWORD:

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: staging
type: Opaque
data:
  SA_PASSWORD:
